version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: rockup-db
    environment:
      POSTGRES_DB: rockup
      POSTGRES_USER: rockup
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"

  ms-message:
    image: ms-message:latest
    container_name: rockup-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/rockup
      SPRING_DATASOURCE_USERNAME: rockup
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - "8080:8080"