spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rockup
    username: rockup
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    generate-ddl: false
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.yml